# https://taskfile.dev

version: "3"

dotenv:
  - .env

tasks:
  tidy-go:
    internal: true
    cmds:
      - go mod tidy

  tidy-js:
    internal: true
    cmds:
      - pnpm install

  tidy-py:
    internal: true
    cmds:
      - uv sync --all-packages

  tidy:
    deps:
      - tidy-go
      - tidy-js
      - tidy-py

  format-check:
    cmds:
      - goimports -e -l .

  format:
    cmds:
      - goimports -w .

  lint:
    cmds:
      - golangci-lint run

  build-go:
    cmds:
      - go tool goreleaser build {{.CLI_ARGS}}

  build-py:
    internal: true
    cmds:
      - uv build --all-packages

  build:
    cmds:
      - task: build-go
        vars:
          CLI_ARGS: "--snapshot --clean --skip before"
      - go run ./buildscripts/postbuild/postbuild.go
      - task: build-py

  release:
    cmds:
      - go tool goreleaser release
      - go run ./buildscripts/postbuild/postbuild.go
      - task: build-py
      - pnpm publish -r --access public --no-git-checks
      - uv publish

  dev:
    cmds:
      - go tool wgo -file .go go tool task build-go -- --single-target --skip before --snapshot --clean

  run:
    cmds:
      - go run ./main.go {{.CLI_ARGS}}

  add-command:
    cmds:
      - scf ./templates/command ./internal/cmd
