name: PR
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Install deps
        run: |
          go mod tidy
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Format
        run: go tool task format-check

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56

      - name: Build
        run: go tool task build
